fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.13.1
    logrotate: git://github.com/voxpupuli/puppet-logrotate.git
  symlinks:
    nhc: "#{source_dir}"
