fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.25.0
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      ref: 1.0.1
      puppet_version: ">= 6.0.0"
    logrotate: git://github.com/voxpupuli/puppet-logrotate.git
    yum:
      repo: https://github.com/voxpupuli/puppet-yum.git
  symlinks:
    nhc: "#{source_dir}"
