fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    vcsrepo:
      repo: puppetlabs/vcsrepo
    logrotate:
      repo: puppet/logrotate
    yum:
      repo: puppet/yum
    # Needed by logrotate
    systemd:
      repo: puppet/systemd
  symlinks:
    nhc: "#{source_dir}"
