---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - ---el7
      - el8
      - el9
      - debian-11
      - debian-12
      - ubuntu-2004
      - ubuntu-2204
    puppet:
      - puppet7
      - puppet8
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
.rubocop.yml:
  profiles:
    strict:
      configs:
        RSpec/MultipleMemoizedHelpers:
          Enabled: false
        RSpec/RepeatedExampleGroupBody:
          Enabled: false
spec/acceptance/nodesets/el7.yml:
  packages:
    - git
spec/acceptance/nodesets/el8.yml:
  packages:
    - git
spec/acceptance/nodesets/el9.yml:
  packages:
    - git
spec/acceptance/nodesets/debian-11.yml:
  packages:
    - git
spec/acceptance/nodesets/debian-12.yml:
  packages:
    - git
spec/acceptance/nodesets/ubuntu-2004.yml:
  packages:
    - cron
    - git
spec/acceptance/nodesets/ubuntu-2204.yml:
  packages:
    - cron
    - git
